/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-upcloud-api/apis/firewall/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeRuleses implements RulesInterface
type FakeRuleses struct {
	Fake *FakeFirewallV1alpha1
	ns   string
}

var rulesesResource = schema.GroupVersionResource{Group: "firewall.upcloud.kubeform.com", Version: "v1alpha1", Resource: "ruleses"}

var rulesesKind = schema.GroupVersionKind{Group: "firewall.upcloud.kubeform.com", Version: "v1alpha1", Kind: "Rules"}

// Get takes name of the rules, and returns the corresponding rules object, and an error if there is any.
func (c *FakeRuleses) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Rules, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(rulesesResource, c.ns, name), &v1alpha1.Rules{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Rules), err
}

// List takes label and field selectors, and returns the list of Ruleses that match those selectors.
func (c *FakeRuleses) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.RulesList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(rulesesResource, rulesesKind, c.ns, opts), &v1alpha1.RulesList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.RulesList{ListMeta: obj.(*v1alpha1.RulesList).ListMeta}
	for _, item := range obj.(*v1alpha1.RulesList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested ruleses.
func (c *FakeRuleses) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(rulesesResource, c.ns, opts))

}

// Create takes the representation of a rules and creates it.  Returns the server's representation of the rules, and an error, if there is any.
func (c *FakeRuleses) Create(ctx context.Context, rules *v1alpha1.Rules, opts v1.CreateOptions) (result *v1alpha1.Rules, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(rulesesResource, c.ns, rules), &v1alpha1.Rules{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Rules), err
}

// Update takes the representation of a rules and updates it. Returns the server's representation of the rules, and an error, if there is any.
func (c *FakeRuleses) Update(ctx context.Context, rules *v1alpha1.Rules, opts v1.UpdateOptions) (result *v1alpha1.Rules, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(rulesesResource, c.ns, rules), &v1alpha1.Rules{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Rules), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeRuleses) UpdateStatus(ctx context.Context, rules *v1alpha1.Rules, opts v1.UpdateOptions) (*v1alpha1.Rules, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(rulesesResource, "status", c.ns, rules), &v1alpha1.Rules{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Rules), err
}

// Delete takes name of the rules and deletes it. Returns an error if one occurs.
func (c *FakeRuleses) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(rulesesResource, c.ns, name), &v1alpha1.Rules{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeRuleses) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(rulesesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.RulesList{})
	return err
}

// Patch applies the patch and returns the patched rules.
func (c *FakeRuleses) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Rules, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(rulesesResource, c.ns, name, pt, data, subresources...), &v1alpha1.Rules{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Rules), err
}
