/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	floatingv1alpha1 "kubeform.dev/provider-upcloud-api/apis/floating/v1alpha1"
	versioned "kubeform.dev/provider-upcloud-api/client/clientset/versioned"
	internalinterfaces "kubeform.dev/provider-upcloud-api/client/informers/externalversions/internalinterfaces"
	v1alpha1 "kubeform.dev/provider-upcloud-api/client/listers/floating/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// IpAddressInformer provides access to a shared informer and lister for
// IpAddresses.
type IpAddressInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.IpAddressLister
}

type ipAddressInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewIpAddressInformer constructs a new informer for IpAddress type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewIpAddressInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredIpAddressInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredIpAddressInformer constructs a new informer for IpAddress type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredIpAddressInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.FloatingV1alpha1().IpAddresses(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.FloatingV1alpha1().IpAddresses(namespace).Watch(context.TODO(), options)
			},
		},
		&floatingv1alpha1.IpAddress{},
		resyncPeriod,
		indexers,
	)
}

func (f *ipAddressInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredIpAddressInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *ipAddressInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&floatingv1alpha1.IpAddress{}, f.defaultInformer)
}

func (f *ipAddressInformer) Lister() v1alpha1.IpAddressLister {
	return v1alpha1.NewIpAddressLister(f.Informer().GetIndexer())
}
