/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeform.dev/provider-upcloud-api/apis/managed/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeDatabaseLogicalDatabases implements DatabaseLogicalDatabaseInterface
type FakeDatabaseLogicalDatabases struct {
	Fake *FakeManagedV1alpha1
	ns   string
}

var databaselogicaldatabasesResource = schema.GroupVersionResource{Group: "managed.upcloud.kubeform.com", Version: "v1alpha1", Resource: "databaselogicaldatabases"}

var databaselogicaldatabasesKind = schema.GroupVersionKind{Group: "managed.upcloud.kubeform.com", Version: "v1alpha1", Kind: "DatabaseLogicalDatabase"}

// Get takes name of the databaseLogicalDatabase, and returns the corresponding databaseLogicalDatabase object, and an error if there is any.
func (c *FakeDatabaseLogicalDatabases) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.DatabaseLogicalDatabase, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(databaselogicaldatabasesResource, c.ns, name), &v1alpha1.DatabaseLogicalDatabase{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DatabaseLogicalDatabase), err
}

// List takes label and field selectors, and returns the list of DatabaseLogicalDatabases that match those selectors.
func (c *FakeDatabaseLogicalDatabases) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.DatabaseLogicalDatabaseList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(databaselogicaldatabasesResource, databaselogicaldatabasesKind, c.ns, opts), &v1alpha1.DatabaseLogicalDatabaseList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.DatabaseLogicalDatabaseList{ListMeta: obj.(*v1alpha1.DatabaseLogicalDatabaseList).ListMeta}
	for _, item := range obj.(*v1alpha1.DatabaseLogicalDatabaseList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested databaseLogicalDatabases.
func (c *FakeDatabaseLogicalDatabases) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(databaselogicaldatabasesResource, c.ns, opts))

}

// Create takes the representation of a databaseLogicalDatabase and creates it.  Returns the server's representation of the databaseLogicalDatabase, and an error, if there is any.
func (c *FakeDatabaseLogicalDatabases) Create(ctx context.Context, databaseLogicalDatabase *v1alpha1.DatabaseLogicalDatabase, opts v1.CreateOptions) (result *v1alpha1.DatabaseLogicalDatabase, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(databaselogicaldatabasesResource, c.ns, databaseLogicalDatabase), &v1alpha1.DatabaseLogicalDatabase{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DatabaseLogicalDatabase), err
}

// Update takes the representation of a databaseLogicalDatabase and updates it. Returns the server's representation of the databaseLogicalDatabase, and an error, if there is any.
func (c *FakeDatabaseLogicalDatabases) Update(ctx context.Context, databaseLogicalDatabase *v1alpha1.DatabaseLogicalDatabase, opts v1.UpdateOptions) (result *v1alpha1.DatabaseLogicalDatabase, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(databaselogicaldatabasesResource, c.ns, databaseLogicalDatabase), &v1alpha1.DatabaseLogicalDatabase{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DatabaseLogicalDatabase), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeDatabaseLogicalDatabases) UpdateStatus(ctx context.Context, databaseLogicalDatabase *v1alpha1.DatabaseLogicalDatabase, opts v1.UpdateOptions) (*v1alpha1.DatabaseLogicalDatabase, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(databaselogicaldatabasesResource, "status", c.ns, databaseLogicalDatabase), &v1alpha1.DatabaseLogicalDatabase{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DatabaseLogicalDatabase), err
}

// Delete takes name of the databaseLogicalDatabase and deletes it. Returns an error if one occurs.
func (c *FakeDatabaseLogicalDatabases) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(databaselogicaldatabasesResource, c.ns, name), &v1alpha1.DatabaseLogicalDatabase{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDatabaseLogicalDatabases) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(databaselogicaldatabasesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.DatabaseLogicalDatabaseList{})
	return err
}

// Patch applies the patch and returns the patched databaseLogicalDatabase.
func (c *FakeDatabaseLogicalDatabases) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.DatabaseLogicalDatabase, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(databaselogicaldatabasesResource, c.ns, name, pt, data, subresources...), &v1alpha1.DatabaseLogicalDatabase{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DatabaseLogicalDatabase), err
}
