apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: upcloud.kubeform.com
    app.kubernetes.io/part-of: kubeform.com
  name: storages.storage.upcloud.kubeform.com
spec:
  group: storage.upcloud.kubeform.com
  names:
    kind: Storage
    listKind: StorageList
    plural: storages
    singular: storage
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            properties:
              backendRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              providerRef:
                description: LocalObjectReference contains enough information to let
                  you locate the referenced object inside the same namespace.
                properties:
                  name:
                    description: 'Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                      TODO: Add other useful fields. apiVersion, kind, uid?'
                    type: string
                type: object
              resource:
                properties:
                  backupRule:
                    description: "The criteria to backup the storage \t\tPlease keep
                      in mind that it's not possible to have a server with backup_rule
                      attached to a server with simple_backup specified. \t\tSuch
                      configurations will throw errors during execution. \t\tAlso,
                      due to how UpCloud API works with simple backups and how Terraform
                      orders the update operations, \t\tit is advised to never switch
                      between simple_backup on the server and individual storages
                      backup_rules in one apply. \t\tIf you want to switch from using
                      server simple backup to per-storage defined backup rules, \t\tplease
                      first remove simple_backup block from a server, run 'terraform
                      apply', \t\tthen add 'backup_rule' to desired storages and run
                      'terraform apply' again."
                    properties:
                      interval:
                        description: The weekday when the backup is created
                        type: string
                      retention:
                        description: The number of days before a backup is automatically
                          deleted
                        format: int64
                        type: integer
                      time:
                        description: The time of day when the backup is created
                        type: string
                    required:
                    - interval
                    - retention
                    - time
                    type: object
                  clone:
                    description: Block defining another storage/template to clone
                      to storage
                    properties:
                      ID:
                        description: The unique identifier of the storage/template
                          to clone
                        type: string
                    required:
                    - ID
                    type: object
                  id:
                    type: string
                  import:
                    description: Block defining external data to import to storage
                    properties:
                      sha256sum:
                        description: sha256 sum of the imported data
                        type: string
                      source:
                        description: The mode of the import task. One of `http_import`
                          or `direct_upload`.
                        type: string
                      sourceHash:
                        description: For `direct_upload`; an optional hash of the
                          file to upload.
                        type: string
                      sourceLocation:
                        description: The location of the file to import. For `http_import`
                          an accessible URL for `direct_upload` a local file.
                        type: string
                      writtenBytes:
                        description: Number of bytes imported
                        format: int64
                        type: integer
                    required:
                    - source
                    - sourceLocation
                    type: object
                  size:
                    description: The size of the storage in gigabytes
                    format: int64
                    type: integer
                  tier:
                    description: The storage tier to use
                    type: string
                  title:
                    description: A short, informative description
                    type: string
                  zone:
                    description: The zone in which the storage will be created
                    type: string
                required:
                - size
                - title
                - zone
                type: object
              state:
                properties:
                  backupRule:
                    description: "The criteria to backup the storage \t\tPlease keep
                      in mind that it's not possible to have a server with backup_rule
                      attached to a server with simple_backup specified. \t\tSuch
                      configurations will throw errors during execution. \t\tAlso,
                      due to how UpCloud API works with simple backups and how Terraform
                      orders the update operations, \t\tit is advised to never switch
                      between simple_backup on the server and individual storages
                      backup_rules in one apply. \t\tIf you want to switch from using
                      server simple backup to per-storage defined backup rules, \t\tplease
                      first remove simple_backup block from a server, run 'terraform
                      apply', \t\tthen add 'backup_rule' to desired storages and run
                      'terraform apply' again."
                    properties:
                      interval:
                        description: The weekday when the backup is created
                        type: string
                      retention:
                        description: The number of days before a backup is automatically
                          deleted
                        format: int64
                        type: integer
                      time:
                        description: The time of day when the backup is created
                        type: string
                    required:
                    - interval
                    - retention
                    - time
                    type: object
                  clone:
                    description: Block defining another storage/template to clone
                      to storage
                    properties:
                      ID:
                        description: The unique identifier of the storage/template
                          to clone
                        type: string
                    required:
                    - ID
                    type: object
                  id:
                    type: string
                  import:
                    description: Block defining external data to import to storage
                    properties:
                      sha256sum:
                        description: sha256 sum of the imported data
                        type: string
                      source:
                        description: The mode of the import task. One of `http_import`
                          or `direct_upload`.
                        type: string
                      sourceHash:
                        description: For `direct_upload`; an optional hash of the
                          file to upload.
                        type: string
                      sourceLocation:
                        description: The location of the file to import. For `http_import`
                          an accessible URL for `direct_upload` a local file.
                        type: string
                      writtenBytes:
                        description: Number of bytes imported
                        format: int64
                        type: integer
                    required:
                    - source
                    - sourceLocation
                    type: object
                  size:
                    description: The size of the storage in gigabytes
                    format: int64
                    type: integer
                  tier:
                    description: The storage tier to use
                    type: string
                  title:
                    description: A short, informative description
                    type: string
                  zone:
                    description: The zone in which the storage will be created
                    type: string
                required:
                - size
                - title
                - zone
                type: object
              terminationPolicy:
                enum:
                - Delete
                - DoNotTerminate
                type: string
              updatePolicy:
                enum:
                - Destroy
                - DoNotDestroy
                type: string
            required:
            - providerRef
            - resource
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      description: Last time the condition transitioned from one status
                        to another. This should be when the underlying condition changed.  If
                        that is not known, then using the time when the API field
                        changed is acceptable.
                      format: date-time
                      type: string
                    message:
                      description: A human readable message indicating details about
                        the transition. This field may be empty.
                      type: string
                    observedGeneration:
                      description: If set, this represents the .metadata.generation
                        that the condition was set based upon. For instance, if .metadata.generation
                        is currently 12, but the .status.condition[x].observedGeneration
                        is 9, the condition is out of date with respect to the current
                        state of the instance.
                      format: int64
                      type: integer
                    reason:
                      description: The reason for the condition's last transition
                        in CamelCase. The specific API may choose whether or not this
                        field is considered a guaranteed API. This field may not be
                        empty.
                      type: string
                    status:
                      description: Status of the condition, one of True, False, Unknown.
                      type: string
                    type:
                      description: Type of condition in CamelCase or in foo.example.com/CamelCase.
                        Many .condition.type values are consistent across resources
                        like Available, but because arbitrary conditions can be useful
                        (see .node.status.conditions), the ability to deconflict is
                        important.
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              observedGeneration:
                description: Resource generation, which is updated on mutation by
                  the API Server.
                format: int64
                type: integer
              phase:
                description: Status defines the set of statuses a resource can have.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
